---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - ansible
        - cron
        - git
        - htop
        - keychain
        - neovim
        - net-tools
        - openssh-server
        - openssh-client
        - ranger
        - rsync
        - tmux

  - name: add ansible user
    user:
      name: ansible
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/jordanjcp/ansible_setup.git

  - name: Clone config repo to home/ansible/repos
    git:
      repo: https://github.com/jordanjcp/config.git
      dest: /home/ansible/repos/config
      separate_git_dir: /home/ansible/repos/config_git

  - name: copy bash config for user jordan
    copy:
      src: /home/ansible/repos/config/bash
      dest: /home/jordan/.config/
      owner: jordan
      group: jordan

  - name: symbolic link .bashrc for user jordan
    file:
      src: /home/jordan/.config/bash/bashrc
      dest: /home/jordan/.bashrc
      force: yes
      owner: jordan
      group: jordan
      state: link
